// <auto-generated />
using System;
using Catalog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Api.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261003150009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Api.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1f0c8a2-4c1e-4b7e-9a51-0f6d2c3a1001"),
                            Currency = "EUR",
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            Sku = "KB-001"
                        },
                        new
                        {
                            Id = new Guid("b1f0c8a2-4c1e-4b7e-9a51-0f6d2c3a1002"),
                            Currency = "EUR",
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            Sku = "MS-001"
                        },
                        new
                        {
                            Id = new Guid("b1f0c8a2-4c1e-4b7e-9a51-0f6d2c3a1003"),
                            Currency = "EUR",
                            Name = "27\" 4K Monitor",
                            Price = 349.00m,
                            Sku = "MN-001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
